%%
% Code to generate Fig. SM3 in Gabaldon et al, 
% "Heuristic Inferencence of the brain dynamical state from the r-spectrum of the correlation matrix"

% Code edited from  "Haimovici et al, Brain Organization into Resting State Networks Emerges at
% Criticality on a Model of the Human Connectome PRL 110, 178101 (2013)"

% This routine plots results from the 'Runs_GH' folder, generated by
% 'GH_simulation_Run.m', and export the data of each plot.

clear all
close all
clc
%Tvec=sort([0.10:0.01:0.22 0.17:0.001:0.18]);  % Vector of values of T: from 0.1 to 0.22. Zoomed about 0.175
Tvec=unique(sort([0.10:0.01:0.22 0.15:0.002:0.18]));  % Vector of values of T: from 0.1 to 0.22. Zoomed about 0.175
rvals=[0:0.001:1]; %r values used to perform the r-spectrum

%Tvec=Tvec(1:22)
%% 
N=5000; % Total nodes in the WS network
%tot_run=10; % Number of independent realizations
run=0
for runx=[1:40]
    run=run+1
    tindex=0;
    for T=Tvec
        tindex=tindex+1;
        load(sprintf('Analysis/ResultsR%d_L%d_T%f.mat',runx,N,T),'rc','AC1','Act')
        tic
        ACx=autocorr(Act);
        AC1=ACx(2); % First autocorrelation coefficient

        
        
        rc.sigm_S1=rc.dS1
        
        
        AllAC1(run,tindex)=AC1;
        AllFa(run,tindex)=mean(Act);
        Allrc_S2(run,tindex)=rc.S2;
        Allrc_sigm_S1(run,tindex)=rc.sigm_S1;
        Allrc_LG(run,tindex)=rc.LG;
     
        
   

    end  
end
tot_run=size(AllAC1,1)
% plots

figure(1400)

subplot(221)

plot(Tvec,mean(AllFa),'k-o')
xlabel('T')
ylabel('Fa')

subplot(222)
hold on
errorbar(Tvec,mean(AllAC1),std(AllAC1)/sqrt(tot_run),'-o')
ylabel('AC(1)')
xlabel('T')

subplot(223)
hold on
errorbar(Tvec,mean(Allrc_S2),std(Allrc_S2)/sqrt(tot_run),'-o')
errorbar(Tvec,mean(Allrc_sigm_S1),std(Allrc_sigm_S1)/sqrt(tot_run),'-o')
errorbar(Tvec,mean(Allrc_LG),std(Allrc_LG)/sqrt(tot_run),'-o')
ylabel('rc')
xlabel('T')
legend("S2", "\sigma S_1", "L(G)")


subplot(224)
plot(mean(AllAC1),mean(Allrc_S2))



toc

%% Export data
mkdir('FiguresData')
X=cat(2,Tvec',mean(AllFa,1)',std(AllFa,1)'/sqrt(tot_run));
save('FiguresData/Fa_vs_Th.dat', 'X', '-ascii', '-double', '-tabs')

X=cat(2,Tvec',mean(AllAC1,1)',std(AllAC1,1)'/sqrt(tot_run));
save('FiguresData/AC1_vs_Th.dat', 'X', '-ascii', '-double', '-tabs')

X=cat(2,Tvec',mean(Allrc_S2,1)',std(Allrc_S2,1)'/sqrt(tot_run));
save('FiguresData/rc_S2_vs_Th.dat', 'X', '-ascii', '-double', '-tabs')

X=cat(2,Tvec',mean(Allrc_sigm_S1,1)',std(Allrc_sigm_S1,1)'/sqrt(tot_run));
save('FiguresData/rc_sigm_S1_vs_Th.dat', 'X', '-ascii', '-double', '-tabs')

X=cat(2,Tvec',mean(Allrc_LG,1)',std(Allrc_LG,1)'/sqrt(tot_run));
save('FiguresData/rc_LG_vs_Th.dat', 'X', '-ascii', '-double', '-tabs')


tcx=18
X=cat(2,mean(AllAC1(:,1:tcx))',mean(Allrc_S2(:,1:tcx))',std(Allrc_S2(:,1:tcx))'/sqrt(tot_run));
save('FiguresData/AC_vs_rcS2SUB.dat', 'X', '-ascii', '-double', '-tabs')

X=cat(2,mean(AllAC1(:,tcx:end))',mean(Allrc_S2(:,tcx:end))',std(Allrc_S2(:,tcx:end))'/sqrt(tot_run));
save('FiguresData/AC_vs_rcS2SUPER.dat', 'X', '-ascii', '-double', '-tabs')



%% Inset variability
figure(1304)
plot(Tvec,std(Allrc_S2),'-o')
hold on
plot(Tvec,std(Allrc_sigm_S1),'-o')
plot(Tvec,std(Allrc_LG),'-o')


X=cat(2,Tvec',std(Allrc_S2)',std(Allrc_LG)',std(Allrc_sigm_S1)');
save('FiguresData/rc_variability.dat', 'X', '-ascii', '-double', '-tabs')